return {
  -- "dnlhc/glance.nvim",
  -- cmd = "Glance",
  -- keys = {
  --   { "gD", "<CMD>Glance definitions<CR>" },
  --   { "gR", "<CMD>Glance references<CR>" },
  --   { "gY", "<CMD>Glance type_definitions<CR>" },
  --   { "gM", "<CMD>Glance implementations<CR>" },
  -- },
  -- opts = function()
  --   local actions = require("glance").actions
  --   return {
  --     folds = {
  --       fold_closed = "󰅂", -- 󰅂 
  --       fold_open = "󰅀", -- 󰅀 
  --       folded = true,
  --     },
  --     mappings = {
  --       list = {
  --         ["<C-u>"] = actions.preview_scroll_win(5),
  --         ["<C-d>"] = actions.preview_scroll_win(-5),
  --         ["sg"] = actions.jump_vsplit,
  --         ["sv"] = actions.jump_split,
  --         ["st"] = actions.jump_tab,
  --         ["p"] = actions.enter_win("preview"),
  --       },
  --       preview = {
  --         ["q"] = actions.close,
  --         ["p"] = actions.enter_win("list"),
  --       },
  --     },
  --   }
  -- end,
}
