-- @TODO: Testing out conform, might just delete this
return {
  -- "nvimtools/none-ls.nvim",
  -- config = function()
  --   -- local null_ls = require("null-ls")
  --   --
  --   -- null_ls.setup({
  --   --   sources = {
  --   --     null_ls.builtins.formatting.rustfmt.with({
  --   --       condition = function(utils)
  --   --         return utils.root_has_file("Cargo.toml")
  --   --       end,
  --   --     }),
  --   --     null_ls.builtins.formatting.stylua,
  --   --     null_ls.builtins.formatting.prettier,
  --   --     null_ls.builtins.diagnostics.editorconfig_checker,
  --   --     null_ls.builtins.diagnostics.eslint_d,
  --   --   },
  --   -- })
  -- end,
}
