return {
  -- {
  -- 	"vhyrro/luarocks.nvim",
  -- 	priority = 1000,
  -- 	config = true,
  -- 	opts = {
  -- 		rocks = { "lua-curl", "nvim-nio", "mimetypes", "xml2lua" },
  -- 	},
  -- },
  -- {
  -- 	"rest-nvim/rest.nvim",
  -- 	dependencies = { "luarocks.nvim" },
  -- 	config = function()
  -- 		require("rest-nvim").setup({
  -- 			result = {
  -- 				split = {
  -- 					-- Open request results in a horizontal split
  -- 					horizontal = false,
  -- 					-- Keep the http file buffer above|left when split horizontal|vertical
  -- 					in_place = false,
  -- 					-- stay in current windows (.http file) or change to results window (default)
  -- 					stay_in_current_window_after_split = false,
  -- 				},
  -- 				behavior = {
  -- 					show_info = {
  -- 						-- toggle showing URL, HTTP info, headers at top the of result window
  -- 						url = true,
  -- 						-- show the generated curl command in case you want to launch
  -- 						-- the same request via the terminal (can be verbose)
  -- 						curl_command = false,
  -- 						http_info = true,
  -- 						headers = true,
  -- 					},
  -- 					statistics = {
  -- 						enable = true,
  -- 						---@see https://curl.se/libcurl/c/curl_easy_getinfo.html
  -- 						stats = {
  -- 							{ "total_time", title = "Time taken:" },
  -- 							{ "size_download_t", title = "Download size:" },
  -- 						},
  -- 					},
  -- 					-- executables or functions for formatting response body [optional]
  -- 					-- set them to false if you want to disable them
  -- 					formatters = {
  -- 						json = "jq",
  -- 						html = function(body)
  -- 							return vim.fn.system({ "tidy", "-i", "-q", "-" }, body)
  -- 						end,
  -- 					},
  -- 				},
  -- 			},
  -- 			-- Skip SSL verification, useful for unknown certificates
  -- 			skip_ssl_verification = false,
  -- 			-- Encode URL before making request
  -- 			encode_url = true,
  -- 			-- Highlight request on run
  -- 			highlight = {
  -- 				enable = true,
  -- 				timeout = 150,
  -- 			},
  -- 			env_file = ".env",
  -- 			custom_dynamic_variables = {},
  -- 			keybinds = {
  -- 				{ "<leader>rr", "<cmd>Rest run<cr>", "Run request under the cursor" },
  -- 				{ "<leader>rl", "<cmd>Rest run last<cr>", "Re-run latest request" },
  -- 			},
  -- 		})
  -- 	end,
  -- },
}
